remove lib/common.sh and add task/test

diff --git a/cmd/repo-tag b/cmd/repo-tag
--- a/cmd/repo-tag
+++ b/cmd/repo-tag
@@ -20,9 +20,82 @@
 # * .tags subdir is used to commit to ".tags" branch
 #     * if modifying history, "rm -r .tags"
 
-pkg="$(readlink -f -- "$0")"
-pkg="${pkg%/*/*}"
-. "$pkg/lib/common.sh"
+# COMMON
+    quiet=false
+    fatal() { rc="$1"; shift; printf %s\\n "${0##*/} error: $*" >&2 || true; exit "$rc"; }
+    nonfatal() { $quiet || printf %s\\n "${0##*/}: $*" >&2 || true; }
+
+    _save_semver() {
+        saved_semver="${semver:-}"
+        saved_major="${major:-}"
+        saved_minor="${minor:-}"
+        saved_patch="${patch:-}"
+        saved_ver_pre="${ver_pre:-}"
+        saved_ver_meta="${ver_meta:-}"
+        }
+    _unsave_semver() {
+        semver="$saved_semver"
+        major="$saved_major"
+        minor="$saved_minor"
+        patch="$saved_patch"
+        ver_pre="$saved_ver_pre"
+        ver_meta="$saved_ver_meta"
+        }
+    _parse_semver() {
+        semver="$1"
+        case "$1" in
+            [!0123456789]*) return 1 ;;
+            *+) return 1 ;;
+            *+*)
+                ver_meta="${1#*+}"
+                set -- "${1%%+*}"
+                ;;
+            *) ver_meta= ;;
+            esac
+        # TODO: better validate ver_meta
+        case "$1" in
+            [0123456789]*.[0123456789]*.[0123456789]*) ;;
+            *) return 1 ;;
+            esac
+        major="${1%%.*}"
+        ver_pre="${1#*.}"
+        minor="${ver_pre%%.*}"
+        ver_pre="${ver_pre#*.}"
+        patch="${ver_pre%%-*}"
+        case "$ver_pre" in
+            *-) return 1 ;;
+            *-*) ver_pre="${ver_pre#*-}" ;;
+            *) ver_pre= ;;
+            esac
+        # TODO: better validate ver_pre
+        case "$major$minor$patch" in *[!0123456789]*) return 1 ;; esac
+        case ".$major.$minor.$patch." in
+            *.0[!.]*) return 1 ;;
+            esac
+        }
+    parse_semver() {  # STR
+        # sets variables: semver, major, minor, patch, ver_pre, ver_meta
+        # semver 2.0.0
+        _save_semver
+        _parse_semver "$1" || { _unsave_semver; return 1; }
+        }
+    set_greater_semver() {  # STR
+        # if STR in semver format, parse the greater semver
+        parse_semver "$1" || return 0
+        [ $major -le $saved_major ] || return 0
+        [ $major =   $saved_major ] || { _unsave_semver; return 0; }
+        [ $minor -le $saved_minor ] || return 0
+        [ $minor =   $saved_minor ] || { _unsave_semver; return 0; }
+        [ $patch -le $saved_patch ] || return 0
+        [ $patch =   $saved_patch ] || { _unsave_semver; return 0; }
+        }
+
+    hg_is_pristine() {  # [-Rrepo]
+        # "pristine" = clean without unknown files
+        # hg identify doesn't consider unknown files when marking clean/dirty
+        [ -z "$(hg status "$@" | head -n1)" ]
+        }
+
 handle_option() {
     case "$1" in
         quiet)
@@ -60,7 +133,7 @@ while [ $# -gt 0 ]; do
         --:) shift ;;
         --:*|--*[\ \`\~\!\@\#\$\%\^\&\*\\\|\;\'\"\?]*) fatal 64 'bad option name' ;;
         --*) handle_option "${1#--}"; shift ;;
-        -*[\ \`\~\!\@\#\$\%\^\&\*\=\\\|\;\'\"\?]*) fatal 64 'bad option name' ;;
+        -[\ \`\~\!\@\#\$\%\^\&\*\=\\\|\;\'\"\?]*) fatal 64 'bad option name' ;;
         -:*)
             x="${1#??}"
             shift
@@ -92,7 +165,7 @@ else
     # TODO: auto-increment prerelease? prevent skipping numeric parts?
     ver_suffix="-$1"
     fi
-version="$("$pkg/cmd/repo-version" --quiet)"
+version="$("${0%/*}/repo-version" --quiet)"
 version="${version%%+*}"
 case "$version" in
     *-*) ;;
diff --git a/task/test b/task/test
--- a/task/test
+++ b/task/test
@@ -1,2 +1,17 @@
 #!/bin/sh -Cue
-true
+cd "${0%/*}/.."
+exec </dev/null >&2
+fatal() { rc="$1"; shift; printf %s\\n "${0##*/} error: $*" >&2 || true; exit "$rc"; }
+while [ $# -gt 0 ]; do case "$1" in --) shift; break ;; -) break ;; -*) fatal 64 'unexpected option' ;; *) break ;; esac; done
+[ $# = 0 ] || fatal 64 'unexpected arguments'
+
+if [ -e task/build ]; then
+    task/build
+    fi
+
+[ -e test ] || fatal 0 "missing: $(pwd)/test"
+[ -d test ] || fatal 70 "not a directory: $(pwd)/test"
+which redo-ifchange >/dev/null 2>&1 || fatal 69 'missing command: redo-ifchange'
+find test -name '.?*' -prune -o -type f -name '*.test' -print |
+sed 's/\.test$/.diff/' |
+xargs -d\\n redo-ifchange
